version: '3'

#Services
services:
  frontend: 
    build:
      context: ./frontend
      args: 
        #Django REST (Change url when deploying)
        REACT_APP_API_URL: http://localhost/api
    volumes:
      [react_build:/react-frontend/build]
    stdin_open: true
    networks:
      - network-net

  pgdb:
    image: postgres
    container_name: pgdb
    volumes: 
     [pgdata:/var/lib/postgresql/data]
    networks:
      - network-net
    environment: 
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend:
    build:
      context: ./core_backend
      args:
        #Django (Change credentials for deployment): 
        SECRET_KEY: yoursecretkey
        ALLOWED_HOSTS: http://localhost
        CORS_ORIGIN_WHITELIST: http://localhost:3000
    
        #Postgres (Change credentials for deployment): 
        POSTGRES_TABLE_NAME: dbname
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: pgdb
        POSTGRES_PORT: 5432

    command: bash -c "gunicorn core_backend.wsgi --bind 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    networks:
      - network-net
    depends_on:
      [pgdb]

  nginx:
    image: nginx:latest
    ports: 
      ["80:8080"]
    networks:
      - network-net
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react-frontend
      - ./core_backend/static:/var/www/static
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
  pgdata:

networks:
  #Change network name
  network-net:
    external: true